# @package _global_
defaults:
  - base_gen_optA

representor:
  name: base_gen_stdA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: []