# @package _global_
defaults:
  - base_gen_optA

representor:
  name: base_gen_stdA
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\tilde{Z}]

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: []