name: base
is_on_the_fly: False
is_train: True # whether to train the compressor, if not will load a pretrained representor if it exists
is_use_init: False # useful for using pretrained SSL

loss:
  beta: 1 # this will be `quality` for classical
  beta_anneal: linear