# @package _global_
defaults:
  - cntr

representor:
  name: cntr_mlp

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      norm_layer: "batch"