# @package _global_
defaults:
  - cntr

representor:
  name: cntr_optA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"]
      train_x_augmentations: []