# @package _global_
defaults:
  - cntr_stdA

representor:
  name: cntr_stdA_mlpL

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 3
      norm_layer: "batch"
