# @package _global_
defaults:
  - cntr

representor:
  name: cntr_noA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: []
      train_x_augmentations: []