# @package _global_
defaults:
  - cntr

representor:
  name: cntr_mlpXXS

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 32
      n_hid_layers: 1
      norm_layer: "batch"