# @package _global_
defaults:
  - base@representor
  - override /regularizer: huber
  - override /decodability: contrastive

representor:
  name: cntr_stdA_reg

kwargs:
  decoder_kwargs:
    architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: [x-translation--,y-translation--,rotation--,scale--,shear--] # should have a data standard augmentation
      train_x_augmentations: "a_augmentations"

decodability:
  kwargs:
    is_train_temperature: False
    is_normalize_proj: True
    is_project: True
    is_pred_proj_same: False
    predictor_kwargs: # will be replaced by proojector when `is_pred_proj_same`
      architecture: "linear"
      out_shape: 128
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      norm_layer: "batch"
      out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}

encoder:
  z_shape: 1024
  is_normalize_Z: False

