# @package _global_
defaults:
  - base@representor
  - override /decodability: cissl

representor:
  name: cntr_mlp

decodability:
  kwargs:
    # uses an MLP predictor as the downstream probe
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      out_shape: 128
      norm_layer: "batch"
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}
      norm_layer: "batch"