# @package _global_
defaults:
  - cntr

representor:
  name: cntr_mlpnano

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 10
      n_hid_layers: 1
      norm_layer: "batch"