# @package _global_
defaults:
  - cntr

representor:
  name: cntr_stdA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"] # should have a data standard augmentation
      train_x_augmentations: "a_augmentations"