# @package _global_
defaults:
  - base@representor
  - override /regularizer: cosine
  - override /decodability: contrastive

representor:
  name: cntr

kwargs:
  decoder_kwargs:
    architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "representative"
      a_augmentations: ["label"]
      train_x_augmentations: []

decodability:
  kwargs:
    is_train_temperature: False
    is_normalize_proj: True
    is_project: True
    is_proj_pred_same: False
    predictor_kwargs:
      architecture: "mlp"
      out_shape: 128
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      norm_layer: "batch"
      out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}

encoder:
  z_shape: 1024
  is_normalize_Z: True

