# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: contrastive

representor:
  name: cntr_simclr

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"] # should have a data standard augmentation
      train_x_augmentations: "a_augmentations"

decodability:
  kwargs:
    is_train_temperature: False
    is_pred_proj_same: True
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 1024
      n_hid_layers: 1
      norm_layer: "batch"
      out_shape: 128

encoder:
  z_shape: 512