# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: contrastive

representor:
  name: cntr

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"] # should have a data standard augmentation
      train_x_augmentations: "a_augmentations"

decodability:
  kwargs:
    is_pred_proj_same: False
    is_self_contrastive: True
    predictor_kwargs: # will be replaced by projector when `is_pred_proj_same`
      architecture: "linear"
      out_shape: 128
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}