# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: distillating

representor:
  name: dissl_mlp

decodability:
  kwargs:
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      is_cosine: True