# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: dissl

representor:
  name: dissl

data_repr:
  kwargs:
    dataset_kwargs:
      simclr_aug_strength: 2.0 # increase the strength of simclr augmentation
      a_augmentations: ["blured_simclr"] # add bluring to standard augmentations