# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: dissl

representor:
  name: dissl

decodability:
  kwargs:
    beta_HMlZ: 1.8
    out_dim: 8192
    projector_kwargs:
      architecture: "mlp"
      is_cosine: True