# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: dissl

representor:
  name: dissl

data_repr:
  kwargs:
    dataset_kwargs:
      simclr_aug_strength: 2.0 # increase the strength of simclr augmentation
      a_augmentations: ["blured_simclr"] # add bluring to standard augmentations

decodability:
  kwargs:
    lambda_maximality: 2.3
    beta_HMlZ: 1.8
    out_dim: 8192
    projector_kwargs:
      architecture: "mlp"
      is_cosine: True