# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: distillating

representor:
  name: dissl_mlp

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: "a_augmentations"

decodability:
  kwargs:
    lambda_maximality: 2.3
    beta_HMlZ: 1.8
    out_dim: 8192
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      is_cosine: True