# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: dissl

representor:
  name: dissl

decodability:
  kwargs:
    beta_det_inv: 1.8
    n_equivalence_classes: 8192
    projector_kwargs:
      architecture: "mlp"
      is_cosine: True