# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: distillating

representor:
  name: dissl_mlp

decodability:
  kwargs:
    lambda_maximality: 2.3
    beta_det_inv: 1.8
    n_equivalence_classes: 8192
    projector_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 2
      is_cosine: True