# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: distillating

representor:
  name: dstl

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["blured_simclr"]
      train_x_augmentations: "a_augmentations"