# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: distillating

representor:
  name: dstl_noema_optA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label","data-standard"]
      train_x_augmentations: ["data-standard"]

decodability:
  kwargs:
    ema_weight_prior: null
    beta_pM_unif: 2.3
    beta_HMlZ: 1.8
    out_dim: 16384
    projector_kwargs:
      architecture: "mlp"
      is_cosine: True