# @package _global_
defaults:
  - exact_stdA

representor:
  name: exact_stdA_mlpXS

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 128
      n_hid_layers: 1
      norm_layer: "batch"