# @package _global_
defaults:
  - exact_250A

representor:
  name: exact_250A_mlpL

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 2048
      n_hid_layers: 3
      norm_layer: "batch"