# @package _global_
defaults:
  - exact

representor:
  name: exact_stdA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "Mx"
      a_augmentations: [] # should have a data standard augmentation
      train_x_augmentations: ["data-standard"]
