# @package _global_
defaults:
  - exact

representor:
  name: exact_mlpXXXS

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 16
      n_hid_layers: 1
      norm_layer: "batch"