# @package _global_
defaults:
  - base@representor
  - override /decodability: exact

representor:
  name: exact

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "Mx"
      a_augmentations: ["label"]
      train_x_augmentations: []