# @package _global_
defaults:
  - exact_mlp

representor:
  name: exact_mlpXXS_nobn

decodability:
  kwargs:
    predictor_kwargs:
      architecture: "mlp"
      hid_dim: 32
      n_hid_layers: 1
      norm_layer: "identity"