# @package _global_
defaults:
  - exact

representor:
  name: exact_1000A_shuffle

data_repr:
  kwargs:
    dataset_kwargs:
      n_sub_label: 100 # 100 per label => 1000 in total
      is_shuffle_Mx: True