# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: generative

representor:
  name: gen_stdA
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\tilde{Z}]

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: []

decodability:
  kwargs:
    predecode_n_Mx: 100
    is_batchnorm_pre: True

encoder:
  is_relu_Z: True