# @package _global_
defaults:
  - base@representor
  - override /regularizer: cosine
  - override /decodability: generative

representor:
  name: gen

decodability:
  kwargs:
    decoder_kwargs:
      architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "representative"
      a_augmentations: ["label"]
      train_x_augmentations: []

encoder:
  z_shape: 128
  is_normalize_Z: True

