# @package _global_
defaults:
  - base@representor
  - override /regularizer: cosine
  - override /decodability: generative

representor:
  name: gen_A_pred
  is_switch_x_aux_trgt: False # augmentations will be outputs so R[A|Z]

decodability:
  kwargs:
    decoder_kwargs:
      architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"]
      train_x_augmentations: []

encoder:
  z_shape: 1024
  is_normalize_Z: False

