# @package _global_
defaults:
  - base@representor
  - override /regularizer: prior
  - override /decodability: generative

representor:
  name: gen_vae

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "input"
      a_augmentations: []
      train_x_augmentations: []

encoder:
  kwargs:
    family: diag_gaussian
