# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: generative

representor:
  name: gen_vae

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "input"
      a_augmentations: []
      train_x_augmentations: []


decodability:
  kwargs:
    decoder_kwargs:
      architecture: resnet_transpose
      base: resnet18
      activation: ReLU

encoder:
  z_shape: 512