# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: generative

representor:
  name: gen_std_aug
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\Tilde{Z}]

decodability:
  kwargs:
    decoder_kwargs:
      architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: [x-translation--,y-translation--,rotation--,scale--,shear--]
      train_x_augmentations: []

encoder:
  z_shape: 128
  is_normalize_Z: False

