# @package _global_
defaults:
  - base@representor
  - override /regularizer: huber
  - override /decodability: generative

representor:
  name: gen_stdA_reg
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\tilde{Z}]
  

decodability:
  kwargs:
    decoder_kwargs:
      architecture: resnet_transpose
      base: resnet18
      activation: Identity

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: []

encoder:
  z_shape: 1024
  is_normalize_Z: False

