# @package _global_
defaults:
  - gen

representor:
  name: gen_permMx

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["perm_label"]
      train_x_augmentations: []