# @package _global_
defaults:
  - base@representor
  - override /regularizer: cosine
  - override /decodability: generative

representor:
  name: gen_mlp
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\Tilde{Z}]

decodability:
  kwargs:
    decoder_kwargs:
      architecture: mlp_h2048_l2

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"]
      train_x_augmentations: []

encoder:
  z_shape: 128
  is_normalize_Z: False

