# @package _global_
defaults:
  - gen

representor:
  name: gen_stdA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: [x-translation--,y-translation--,rotation--,scale--,shear--] # should have a data standard augmentation
      train_x_augmentations: "a_augmentations"