# @package _global_
defaults:
  - base_gen_optA

representor:
  name: gen_optA_resnet

decodability:
  kwargs:
    decoder_kwargs:
      architecture: resnet_transpose
      base: resnet18
      activation: ReLU