# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: swav_self_distillation

representor:
  name: slfdstl_swav

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: "a_augmentations"

decodability:
  kwargs:
    n_Mx: 3000
    queue_size: 15
    temperature: 0.1

encoder:
  z_shape: 1024
