# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: simsiam_self_distillation

representor:
  name: slfdstl_simsiam

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: "a_augmentations"

encoder:
  z_shape: 2048
  is_normalize_Z: False

