# @package _global_
  defaults:
    - slfdstl

representor:
  name: slfdstl_optA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"]
      train_x_augmentations: []