# @package _global_
defaults:
  - slfdstl_cluster

representor:
  name: slfdstl_cluster_supA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "representative"
      a_augmentations: ["label"]
      train_x_augmentations: []
