# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: prior_self_distillation

representor:
  name: slfdstl

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: "a_augmentations"

decodability:
  kwargs:
    beta_pM_unif: 1.0 # TODO: tune
    ema_weight_prior: null
    out_dim: 1000
    projector_kwargs:
      architecture: "linear"

encoder:
  z_shape: 1024