# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: prior_self_distillation

representor:
  name: slfdstl

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: "a_augmentations"

encoder:
  is_relu_Z: True