# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: cluster_self_distillation

representor:
  name: slfdstl_cluster

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: [x-translation--,y-translation--,rotation--,scale--,shear--]
      train_x_augmentations: []

decodability:
  kwargs:
    n_Mx: 512
    src_tgt_comparison: symmetric
    queue_size: 10
    is_pred_proj_same: True
    is_process_Mx: False
    is_stop_grad:  True

encoder:
  z_shape: 1024
  is_normalize_Z: False
