# @package _global_
defaults:
  - slfdstl_prior

representor:
  name: slfdstl_prior_noA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: []
      train_x_augmentations: []
