# @package _global_
defaults:
  - slfdstl_prior_supA

representor:
  name: slfdstl_prior_perMx

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["perm_label"]
      train_x_augmentations: []