# @package _global_
defaults:
  - slfdstl

representor:
  name: slfdstl_prior_Hmlz

decodability:
  kwargs:
    beta_H_mlz: 1.0 # currently, not using because KL should take care of minimizing entropy