# @package _global_
defaults:
  - slfdstl_prior

representor:
  name: slfdstl_prior_permMx


data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "representative"
      a_augmentations: ["perm_label"]
      train_x_augmentations: []