# @package _global_
defaults:
  - std_gen

representor:
  name: std_gen_Mx #  R[M(X)|Z]

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "representative"
      a_augmentations: ["label"]
      train_x_augmentations: []
