# @package _global_
defaults:
  - base@representor
  - override /regularizer: huber
  - override /decodability: generative

representor:
  name: std_gen_reg

kwargs:
  decoder_kwargs:
    architecture: cnn

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "input"
      a_augmentations: []
      train_x_augmentations: []

encoder:
  z_shape: 1024
  is_normalize_Z: False

