# @package _global_
defaults:
  - std_cntr

representor:
  name: std_cntr_1000A

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"]
      train_x_augmentations: []
      n_sub_label: 100 # 100 per label => 1000 in total