# @package _global_
defaults:
  - std_cntr

representor:
  name: std_cntr_supA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"] # should have a data standard augmentation
      train_x_augmentations: []
