# @package _global_
defaults:
  - std_gen

representor:
  name: std_gen_stdA
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\tilde{Z}]

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: [x-translation--,y-translation--,rotation--,scale--,shear--]
      train_x_augmentations: []