# @package _global_
defaults:
  - std_gen

representor:
  name: std_gen_supA

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"]
      train_x_augmentations: []