# @package _global_
defaults:
  - std_cntr

representor:
  name: std_cntr_permMx

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["perm_label"]
      train_x_augmentations: []