# @package _global_
defaults:
  - std_gen

representor:
  name: std_gen_permMx

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "representative"
      a_augmentations: ["perm_label"]
      train_x_augmentations: []
