# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: generative

representor:
  name: std_gen_aug
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\tilde{Z}]

kwargs:
  decoder_kwargs:
    architecture: cnn

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"]
      train_x_augmentations: []

encoder:
  z_shape: 128
  is_normalize_Z: False

