# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: generative

representor:
  name: std_gen_V

kwargs:
  decoder_kwargs:
    architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "input"
      a_augmentations: []
      train_x_augmentations: []

encoder:
  z_shape: 128
  is_normalize_Z: False

