# @package _global_
defaults:
  - std_cntr

representor:
  name: std_cntr_asym_permMx

decodability:
  kwargs:
    is_pred_proj_same: False

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["perm_label"]
      train_x_augmentations: []