# @package _global_
defaults:
  - std_gen

representor:
  name: std_gen_permA
  is_switch_x_aux_trgt: True # augmentations will be inputs so R[X|\tilde{Z}]

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["perm_label"]
      train_x_augmentations: []