# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: contrastive

representor:
  name: std_cntr_sup

kwargs:
  decoder_kwargs:
    architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["label"] # should have a data standard augmentation
      train_x_augmentations: []

decodability:
  kwargs:
    is_train_temperature: False
    is_normalize_proj: True
    is_project: True
    is_proj_pred_same: True
    predictor_kwargs:
      architecture: "mlp"
      out_shape: 128
    projector_kwargs:
      architecture: "mlp"
      out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}

encoder:
  z_shape: 128
  is_normalize_Z: True

