# @package _global_
defaults:
  - std_gen

representor:
  name: std_gen_stdA_pred
  is_switch_x_aux_trgt: False # R[A|Z]

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "augmentation"
      a_augmentations: ["data-standard"]
      train_x_augmentations: []
