# @package _global_
defaults:
  - base@representor
  - override /regularizer: none
  - override /decodability: generative

representor:
  name: std_gen_resnetlin

decodability:
  kwargs:
    decoder_kwargs:
      architecture: resnet_transpose
      base: resnet18
      activation: Identity

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target:  "input"
      a_augmentations: []
      train_x_augmentations: []

encoder:
  z_shape: 128
  is_normalize_Z: False

