# @package _global_
defaults:
  - std_cntr

representor:
  name: std_cntr_asym_A

decodability:
  kwargs:
    is_proj_pred_same: False

data_repr:
  kwargs:
    dataset_kwargs:
      train_x_augmentations: []

