name: ???
is_load_last: True # if not loads best to continue training
kwargs:
  dirpath: ${paths.checkpoint}
  monitor: ???
  mode: ???
  verbose: true
  save_last: True
  save_top_k: 1
  save_weights_only: false