defaults:
  - base

name: cosine_restart
# TODO don't think this works currently with lr warmup
modes: ["CosineAnnealingWarmRestarts"] # list of scheduler to use
kwargs:
  # all kwargs
  CosineAnnealingWarmRestarts:
    T_0: 5
    T_mult: 2
    eta_min: 0