name: cosine
#TODO need to add warmup wand use default in SSL literature
modes: ["CosineAnnealingLR"] # list of scheduler to use
kwargs:
  # all kwargs
  CosineAnnealingLR:
    T_max: ${trainer.max_epochs}
    eta_min: 0