defaults:
  - base

name: cosine_nowarm
modes: ["CosineAnnealingLR"] # list of scheduler to use
kwargs:
  # all kwargs
  CosineAnnealingLR:
    T_max: ${trainer.max_epochs}
    eta_min: 0

  base:
    is_warmup_lr: False
    warmup_epochs: 10