name: plateau
modes: ["ReduceLROnPlateau"] # list of scheduler to use
kwargs:
  # all kwargs
  ReduceLROnPlateau:
    mode: min
    factor: 0.2  # factor by which to reduce lr
    patience: 10  # number of epochs with no improvement after which learning rate will be reduced
    threshold: 0.0001 # threshold to be considered "better"
    threshold_mode: rel # relative threshold instead of absolute
    verbose: True
    min_lr: 1e-7 # minimum learning rate
    kwargs_config_scheduler:
      monitor: ${checkpoint.kwargs.monitor}