defaults:
  - base

name: slowwarm_unifmultistep25
modes: ["UniformMultiStepLR"] # list of scheduler to use
kwargs:
  # all kwargs
  UniformMultiStepLR:
    decay_factor: 25
    k_steps: 2

  base:
    is_warmup_lr: True
    warmup_epochs: 0.3