defaults:
  - base

name: warm${format:${.kwargs.base.warmup_epochs},.1e}_unifmultistep_d${.kwargs.UniformMultiStepLR.decay_per_step}
modes: ["UniformMultiStepLR"] # list of scheduler to use
kwargs:
  # all kwargs
  UniformMultiStepLR:
    decay_per_step: 3
    k_steps: null # 3 for <= 300 else 5

  base:
    is_warmup_lr: True
    warmup_epochs: 0.1