# modified from https://arxiv.org/pdf/2007.06346.pdf
defaults:
  - base

name: whitening_quick
modes: ["MultiStepLR"]
kwargs:
  MultiStepLR:
    milestones: [-50,-25]
    gamma: 0.2

  base:
    is_warmup_lr: True
    warmup_epochs: 0.25