# scheduler from https://arxiv.org/pdf/2007.06346.pdf
defaults:
  - base

name: whitening
modes: ["MultiStepLR"]
kwargs:
  MultiStepLR:
    milestones: [-50,-25]
    gamma: 0.1

  base:
    is_warmup_lr: True
    warmup_epochs: 500