# @package _global_
defaults:
  - base_submitit
  - override /hydra/launcher: submitit_slurm

is_nlp_cluster: True

hydra:
  launcher:
    # slurm partition to use on the cluster
    partition: jag-standard # jag-hi, jag-important, jag-standard, john (CPU)
    comment: null
    constraint: null # 12G,11G,24G,pascal,ampere,maxwell,turing,volta
    exclude: jagupard10,jagupard11,jagupard12,jagupard13,jagupard14,jagupard15,jagupard16,jagupard17,jagupard18,jagupard19
    array_parallelism: 30 # max number of parallel tasks

    max_num_timeout: 50 # allow resume from checkpointing
    gres: gpu:${trainer.gpus}