# @package _global_
defaults:
  - base_submitit
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    # slurm partition to use on the cluster
    partition: t4v2 # rtx6000 # cpu,interactive,t4v1,t4v2,p100,rtx6000
    comment: null
    constraint: null
    exclude: null
    array_parallelism: 30

    max_num_timeout: 30 # allow resume from checkpointing
    additional_parameters:
      qos: normal # normal, high, deadline, nopreemption (this is the stream of execution )

# NOTE:
# I also had to change the command in submitit. specifically in submitit/slurm/slurm
# somewhere : /h/yannd/.conda/envs/lossyless/lib/python3.8/site-packages/submitit/slurm/
# function: _make_sbatch_string replace the end with
# lines += [
#       "",
#       "# command",
#       "export SUBMITIT_EXECUTOR=slurm",
#       "export MKL_THREADING_LAYER=GNU",
#       f"srun --mem {mem} --output '{stdout}' --error '{stderr}' --unbuffered {command}",
#   ]
#
# and also had to add slurm to the path
# export PATH="$PATH:/opt/slurm/bin"