defaults:
  - base_self_distillation

kwargs:
  mode: assign_self_distillation
  beta_pM_unif: 1.7 # TODO: tune
  beta_HMlZ: 1.7 # cannot be less than one
  ema_weight_prior: 0.7
  out_dim: 16384
  temperature: 1
  temperature_assign: null # by default half of temperature
  projector_kwargs:
    architecture:  "linear"
    bottleneck_size: null # bottleneck for the last layer, ie, low rank approx