defaults:
  - base

name: base_contrastive
mode: contrastive
z_shape: ${encoder.out_shape}
is_train_temperature: True
is_normalize_proj: True
effective_batch_size: none
is_already_represented: False
is_project:  True
src_tgt_comparison: "all"
is_symmetric_projector: True
predictor_kwargs:
  mode: "linear"
  out_shape: 128
projector_kwargs:
  mode: "mlp"
  out_shape: ${.predictor_kwargs.out_shape}