defaults:
  - base_self_distillation

kwargs:
  mode: cluster_self_distillation
  n_Mx: 512
  freeze_Mx_epochs:  1
  src_tgt_comparison: symmetric
  temperature:  0.1
  queue_size:  30
  sinkhorn_kwargs:
    eps: 0.05
  is_normalize_proj:  True
  is_pred_proj_same:  True # use no predictor by default
