defaults:
  - base

# all arguments to ContrastiveISSL (see docstrings)
kwargs:
  mode: contrastive
  z_shape: ${encoder.z_shape}
  temperature: 0.07
  is_pred_proj_same: True # whether to use the same projection head on both branches (ie SimCLR) instead of asymmetric projector/predictor as in CISSL
  is_self_contrastive: False
  is_batchnorm_post: True
  is_batchnorm_pre: False
  loss: ce
  predictor_kwargs:
    architecture: "linear"
    out_shape: ${encoder.z_shape}
  projector_kwargs:
    architecture: "mlp"
    out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}
    hid_dim: 1024
    n_hid_layers: 1