defaults:
  - base

kwargs:
  mode: contrastive
  z_shape: ${encoder.z_shape}
  temperature: 0.07
  is_train_temperature: False
  is_cosine_neg_temperature: False
  is_cosine_pos_temperature: False
  n_epochs: ${trainer.max_epochs}
  is_pred_proj_same: True
  is_self_contrastive: False
  is_batchnorm_post: True
  is_batchnorm_pre: False
  is_margin_loss: False
  predictor_kwargs:
    architecture: "linear"
    out_shape: ${encoder.z_shape}
  projector_kwargs:
    architecture: "mlp"
    out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}