defaults:
  - base

factor_beta: 1 # TODO: change to 0.01 (although not clear whether it's huber that should get it or whether it's contrastive)
kwargs:
  mode: contrastive
  z_shape: ${encoder.z_shape}
  temperature: 0.07
  is_train_temperature: False
  is_aux_already_represented: ${data.is_aux_already_represented}
  src_tgt_comparison: "all"
  is_pred_proj_same: True
  is_self_contrastive: 'yes' # TODO will have to be true or false
  predictor_kwargs:
    architecture: "flatten"
    out_shape: ${encoder.z_shape}
  projector_kwargs:
    architecture: "mlp"
    out_shape: ${decodability.kwargs.predictor_kwargs.out_shape}