defaults:
  - contrastive

factor_beta: 1 # TODO: ???
kwargs:
  is_normalize_proj: True
  is_project:  False
  src_tgt_comparison: "all"
  is_pred_proj_same: False
  is_hinge: True
  is_kernel: True
  kernel_kwargs:
    is_normalize: False
    pre_gamma_init: 0.0
    is_linear: True