defaults:
  - base

# all arguments to DISSL (see docstrings)
kwargs:
  mode: dissl
  ### the following three hyperparameters are worth tuning ###
  lambda_maximality: 2.3 # maximality hyperparameter to tune (typically [1.8,2.8])
  beta_det_inv: 0.8 # determinism+invariance hyperparameter (typically [0.4,1])
  n_equivalence_classes: 16384 # number of equivalent classes (ie C in the paper)
  #############################################################
  projector_kwargs:
    architecture: "mlp"
    bottleneck_size: ${decodability.kwargs.predictor_kwargs.bottleneck_size}
    hid_dim: 1024
    n_hid_layers: 1
    norm_layer: "batch"
  predictor_kwargs:
    architecture: "linear"
    bottleneck_size: 512 # bottleneck for the last layer, ie, low rank approx