# @package _global_
defaults:
  - base

decodability:
  factor_beta: 1
  kwargs:
    mode: exact
    z_shape: ${encoder.z_shape}
    m_shape: ${data.aux_shape}
    loss:  CrossEntropyLoss
    predictor_kwargs: 
      architecture: linear

data_repr:
  kwargs:
    dataset_kwargs:
      aux_target: "Mx" # get the actual underlying maximal invariant