defaults:
  - base

factor_beta: 100
is_reconstruct: True # can reconstruct images
kwargs:
  mode: generative
  z_shape: ${encoder.z_shape}
  a_shape: ${data.aux_shape}
  is_batchnorm_pre: False
  decoder_kwargs:
    architecture: linear
  predecode_n_Mx: null
  predecoder_kwargs:
    architecture: linear
  normalized: ${data.normalized}
  softmax_kwargs:
    n_steps: ${data.max_steps}
    is_gumbel: True
    temperature_mode: "train"
    temperature: 3
  pred_loss_kwargs:
    is_classification: ${data.aux_is_clf}