defaults:
  - base_self_distillation

kwargs:
  mode: prior_self_distillation
  is_symmetric_loss: True
  beta_pM_unif: 1.0 # TODO: tune
  ema_weight_prior: null
  out_dim: 1000
  is_symmetric_KL_H: True
  freeze_predictor_epochs: 0
  is_normalize_logits: False
  predictor_kwargs:
    architecture: "linear"
  projector_kwargs:
    architecture: {.kwargs.predictor_kwargs}