defaults:
  - base_self_distillation

kwargs:
  mode: prior_self_distillation
  beta_pM_unif: 1.0 # TODO: tune
  ema_weight_prior: null
  out_dim: 1000
  is_batchnorm_pre: True
  projector_kwargs:
    architecture:  "linear"