defaults:
  - base_distillating

kwargs:
  mode: swav_self_distillation
  n_Mx: 1000
  temperature:  0.1
  queue_size:  0
  out_dim: 128
  epoch_queue_starts: 15
  projector_kwargs:
    architecture: "mlp"
    hid_dim: 2048
    n_hid_layers: 1
    norm_layer: batchnorm
