defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

is_force_gpu: True
experiment: ???
agg_mode: [summarize_metrics] # plot_scatter_lines
col_val_subset : {}
fillna: {}
cols_to_str: []
replace: {}
sort: null

patterns:
  # name, pattern to find it
  representor: "results/exp_${experiment}/**/results_representor.csv"
  predictor: "results/exp_${experiment}/**/results_predictor.csv"

collect_data:
  params_to_add: {}

plot_optuna_hypopt:
  storage: sqlite:///${kwargs.base_dir}/results/exp_${experiment}/optuna.db
  study_name: main

kwargs:
  base_dir: ${hydra:runtime.cwd}
  save_dir: results/exp_${experiment}/
  prfx: ""
  dpi: 300
  pretty_renamer: {}
