defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

is_force_gpu: True
experiment: ???
agg_mode: [summarize_metrics] # plot_scatter_lines
col_val_subset : {}
col_cond_subset : {}
fillna: {}
cols_to_str: []
replace: {}
apply: {}
merge_cols: {}
sort: null
base_path: results/exp_${experiment}
job_id_to_rm: []

patterns:
  # name, pattern to find it
  representor: "${base_path}/**/results_representor.csv"
  predictor: "${base_path}/**/results_predictor.csv"

collect_data:
  params_to_add: {}
  params_to_add_dflt : {}
  params_to_create: {}

plot_optuna_hypopt:
  storage: sqlite:///${kwargs.base_dir}/${base_path}/optuna.db
  study_name: main

kwargs:
  base_dir: ${hydra:runtime.cwd}
  save_dir: ${base_path}
  prfx: ""
  dpi: 300
  pretty_renamer: {}
