defaults:
  - base

name: resnet50
kwargs:
  architecture: resnet
  arch_kwargs:
    base: resnet50
    is_channel_out_dim: False # If true changes outputs dimensionality by modifying number of channels before avgpooling