defaults:
  - base

name: resnet18
kwargs:
  architecture: resnet
  arch_kwargs:
    base: resnet18
    is_channel_out_dim: False # If true changes outputs dimensionality by modifying number of channels before avgpooling