# @package _global_
defaults:
  - override /logger: none

# debug the model

experiment: debug_${now:%Y-%m-%d_%H-%M-%S}
timeout: 60

other:
  is_debug: True # enter debug mode
  is_quick: True

trainer:
  # DEBUGGING
  fast_dev_run: True
  weights_summary: full # full to print show the entire model
  profiler: simple # use `simple` or `"advanced"` to find bottleneck
  limit_train_batches: 2
  limit_predict_batches: 2
  limit_test_batches: 2
  limit_val_batches: 2
  max_epochs: 2

callbacks:
  GPUStatsMonitor:
    is_use : False

evaluation:
  representor:
    ckpt_path: null
    is_evaluate: ${representor.is_train}
  predictor:
    ckpt_path: null
    is_evaluate: ${predictor.is_train}