defaults:
  - base_sklearn

# if too slow could significantly improve by using FAISS: https://github.com/scikit-learn-contrib/DESlib/blob/master/deslib/util/faiss_knn_wrapper.py#L19-L203
# or even quicker on GPU: https://machinelearningapplied.com/fast-gpu-based-nearest-neighbors-with-faiss/

metrics: [accuracy_score]
is_scale: True

name: sk_knn
model:
  _target_: sklearn.neighbors.KNeighborsClassifier
  n_neighbors: 5
  weights: uniform
  n_jobs: -1