defaults:
  - base_sklearn

name: sk_mlp
model:
  _target_: sklearn.neural_network.MLPClassifier
  hidden_layer_sizes: (1024,)
  alpha: 0.0001 # regularizer (larger is more regularization)
  max_iter: 200 # n epochs
  random_state: ${seed}