is_sklearn: False
name: torch_mlpw${format:${optimizer_pred.kwargs.weight_decay},.1e}l${format:${optimizer_pred.kwargs.lr},.1e}
kwargs:
  architecture: mlp
  arch_kwargs:
    out_shape: ${data.target_shape}
    # in shape automatic