name: torch_mlpw${format:${optimizer_pred.kwargs.weight_decay},.1e}l${format:${optimizer_pred.kwargs.lr},.1e}
kwargs:
  architecture: mlp
  arch_kwargs:
    out_dim: ${data.target_dim}
    # in shape automatic