defaults:
  - base

name: wandb
is_can_plot_img: true
kwargs:
  save_dir: ${paths.wandb_dir}
  project: issl
  entity: ${wandb_entity}
  group: ${experiment}
  offline: false # Run offline (data can be streamed later to wandb servers).
  reinit: False # ensure that same wandb after preemption
  id: ${job_id}